
-- 4. Search History Table (検索履歴)
create table search_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  city text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (セキュリティ設定) - Search History
alter table search_history enable row level security;

create policy "Individuals can insert their own search history."
  on search_history for insert
  with check ( auth.uid() = user_id );

create policy "Individuals can view their own search history."
  on search_history for select
  using ( auth.uid() = user_id );

create policy "Individuals can delete their own search history."
  on search_history for delete
  using ( auth.uid() = user_id );
