-- 1. Profiles Table (ユーザープロフィール)
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,

  constraint username_length check (char_length(username) >= 3)
);

-- RLS (セキュリティ設定) - Profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. Memos Table (メモ機能)
create table memos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (セキュリティ設定) - Memos
alter table memos enable row level security;

create policy "Individuals can create memos."
  on memos for insert
  with check ( auth.uid() = user_id );

create policy "Individuals can view their own memos."
  on memos for select
  using ( auth.uid() = user_id );

create policy "Individuals can update their own memos."
  on memos for update
  using ( auth.uid() = user_id );

create policy "Individuals can delete their own memos."
  on memos for delete
  using ( auth.uid() = user_id );

-- 3. Auto-create Profile Trigger (ユーザー登録時に自動でプロフィール作成)
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
