
-- 5. Favorites Table (お気に入り)
create table favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  city text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, city)
);

-- RLS (セキュリティ設定) - Favorites
alter table favorites enable row level security;

create policy "Individuals can insert their own favorites."
  on favorites for insert
  with check ( auth.uid() = user_id );

create policy "Individuals can view their own favorites."
  on favorites for select
  using ( auth.uid() = user_id );

create policy "Individuals can delete their own favorites."
  on favorites for delete
  using ( auth.uid() = user_id );
